name: Check style

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  # branches: [ master,develop,feature/* ]
  pull_request:
    branches: [ master,develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: env
        run: |
          env
          pwd
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: /android-app
      - name: linter
        run: |
          gradle lintDebug
          ./gradlew detektDebug
          ./gradlew clean app:compileDebugSources
          ./gradlew ktlintCheck
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: env
        run: |
          env
          pwd
      - name: unit_test
        run: |
          ./gradlew clean :app:testDebugUnitTest
